import { NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { validateMechanicSession } from '@/lib/session';
import { sendSms, createTicketSmsComment, getTicket, updateTicketTags } from '@/lib/bikedesk';
import { buildOfferSmsText } from '@/lib/offer-sms';
import type { OfferSettings, OfferTemplateSnapshot } from '@/types';
import { DEFAULT_OFFER_SETTINGS } from '@/types';

interface SendOfferBody {
  workOrderId: string;
  mechanicId: string;
  mechanicName: string;
  mechanicBikedeskUserId: number | null;
  ticketId: number;
  customerId: number;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  templates: OfferTemplateSnapshot[];
}

export async function POST(req: Request) {
  const mechanic = await validateMechanicSession();
  if (!mechanic) {
    return NextResponse.json({ success: false, error: 'Ikke logget ind' }, { status: 401 });
  }

  let body: SendOfferBody;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ success: false, error: 'Ugyldig forespørgsel' }, { status: 400 });
  }

  if (!body.templates || body.templates.length === 0) {
    return NextResponse.json({ success: false, error: 'Ingen ydelser valgt' }, { status: 400 });
  }

  const supabase = await createServiceClient();

  // Load settings
  const { data: settingsRow } = await supabase
    .from('system_settings')
    .select('value')
    .eq('key', 'offer_settings')
    .single();

  const settings: OfferSettings = settingsRow?.value
    ? { ...DEFAULT_OFFER_SETTINGS, ...(settingsRow.value as Partial<OfferSettings>) }
    : DEFAULT_OFFER_SETTINGS;

  const totalAmount = body.templates.reduce((sum, t) => sum + (t.price ?? 0), 0);
  const expiresAt = new Date(Date.now() + settings.expiry_hours * 60 * 60 * 1000);
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3003';

  // Create offer row (token auto-generated by DB)
  const { data: offer, error: offerError } = await supabase
    .from('offers')
    .insert({
      work_order_id: body.workOrderId,
      mechanic_id: body.mechanicId,
      mechanic_name: body.mechanicName,
      bikedesk_customer_id: body.customerId,
      customer_name: body.customerName,
      customer_phone: body.customerPhone,
      customer_email: body.customerEmail,
      status: 'sent',
      expires_at: expiresAt.toISOString(),
      templates_snapshot: body.templates,
      images_snapshot: [],
      total_amount: totalAmount,
    })
    .select('id, token')
    .single();

  if (offerError || !offer) {
    console.error('[offer/send] DB insert failed', offerError);
    return NextResponse.json({ success: false, error: 'Kunne ikke gemme tilbud' }, { status: 500 });
  }

  // Build and send SMS via BikeDesk
  const smsText = buildOfferSmsText({
    customerName: body.customerName,
    workOrderId: body.workOrderId,
    expiresAt,
    appUrl,
    token: offer.token,
  });

  let smsBatchId: number | undefined;
  try {
    const smsResult = await sendSms({
      message: smsText,
      phone: body.customerPhone,
      customerid: body.customerId,
    });
    smsBatchId = smsResult.batchid;
  } catch (err) {
    console.error('[offer/send] SMS failed', err);
    // Don't fail the offer creation — log the error but continue
  }

  // Log SMS as BikeDesk comment
  if (smsBatchId && body.mechanicBikedeskUserId) {
    try {
      const commentBody = [
        `Tilbud sendt (Sag #${body.workOrderId})`,
        '',
        ...body.templates.map((t) => {
          const icon = t.marker === 'red' ? '▲' : t.marker === 'yellow' ? '▲' : '●';
          return `${icon} ${t.title}${t.price > 0 ? ` — ${t.price} kr.` : ''}`;
        }),
        '',
        `Total: ${totalAmount} kr.`,
        `Udløber: ${expiresAt.toLocaleString('da-DK')}`,
      ].join('\n');

      await createTicketSmsComment({
        ticketId: body.ticketId,
        smsLogId: smsBatchId,
        userId: body.mechanicBikedeskUserId,
        comment: commentBody,
        autocomment: 'sms_other',
      });
    } catch (err) {
      console.error('[offer/send] Comment failed', err);
    }
  }

  // Update ticket tags (tags_on_sent)
  if (settings.tags_on_sent.length > 0) {
    try {
      const ticket = await getTicket(body.ticketId);
      await updateTicketTags(body.ticketId, ticket, settings.tags_on_sent, []);
    } catch (err) {
      console.error('[offer/send] Tag update failed', err);
    }
  }

  // Update offer with batch id
  if (smsBatchId) {
    await supabase
      .from('offers')
      .update({ bikedesk_sms_batch_id: smsBatchId })
      .eq('id', offer.id);
  }

  return NextResponse.json({ success: true, offerId: offer.id });
}
